steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $ErrorView = 'NormalView'
    $VerbosePreference = 'Continue'
    .\build\PSModulePublisher\src\Public\Invoke-Test.ps1 -ModuleManifestPath $env:MODULE_MANIFEST_PATH
  displayName: Test module via module's manifest
