steps:
- pwsh: |
    $matchInfo = $env:BUILD_SOURCEBRANCH | Select-String -Pattern '^refs\/tags\/v((?:\d+\.)+\d+)$'
    $MODULE_VERSION = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    "MODULE_VERSION: '$MODULE_VERSION'" | Write-Host
    # Set job-scoped variables
    echo "##vso[task.setvariable variable=MODULE_VERSION]${MODULE_VERSION}"
  displayName: Process CI variables
