steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    ### Begin CI-specific code: Get the commit tag name
    $matchInfo = $env:BUILD_SOURCEBRANCH | Select-String -Pattern '^refs\/tags\/(.*)'
    $commitTag = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    ### End of CI-specific code
    "Commit tag: '$commitTag'" | Write-Host
    if (!$commitTag) {
        "This is a non-tagged build." | Write-Host
    }else {
        "This is a tagged build." | Write-Host
    }
    $matchInfo = $commitTag | Select-String -Pattern '^v((?:\d+\.)+\d+)$'
    $MODULE_VERSION = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    "MODULE_VERSION: '$MODULE_VERSION'" | Write-Host
    if (!$MODULE_VERSION) {
        "This is a non-release build." | Write-Host
    }else {
        "This is a release build." | Write-Host
    }
    ### Begin CI-specific code: Set job-scoped variables
    echo "##vso[task.setvariable variable=BUILD_COMMIT_TAG]${commitTag}"
    echo "##vso[task.setvariable variable=MODULE_VERSION]${MODULE_VERSION}"
    ### End of CI-specific code
  displayName: Process CI variables
