steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $VerbosePreference = 'Continue'
    .\build\PSModulePublisher\scripts\test.ps1 -ModuleManifestPath $env:MODULE_MANIFEST_PATH
  displayName: Test module via module's manifest
