steps:
- powershell: |
    $ErrorActionPreference = 'Stop'
    $VerbosePreference = 'Continue'
    $MODULE_MANIFEST_PATH = .\build\PSModulePublisher\src\Invoke-Build.ps1
    ### Begin CI-specific code: Set job-scoped variables
    echo "##vso[task.setvariable variable=MODULE_MANIFEST_PATH]${MODULE_MANIFEST_PATH}"
    ### End of CI-specific code
  displayName: Generate module manifest
